version: "3.7"
services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-nestjs_db}
      PGDATA: /data/postgres
    volumes:
      - dbdata:/data/postgres
    ports:
      - '${DB_PORT:-5432}:5432'

volumes:
  dbdata:

    # postgres:
    #   image: 'postgres:15-alpine'
    #   working_dir: /application
    #   volumes:
    #     - '.:/application'
    #   environment:
    #     - POSTGRES_USER=root
    #     - POSTGRES_PASSWORD=docker
    #     - POSTGRES_DB=postgres
    #   ports:
    #     - '29004:5432'
    # services:
    # app:
    #   build: .
    #   entrypoint: .docker/entrypoint.sh
    #   container_name: node
    #   ports:
    #     - 3000:3000
    #   volumes:
    #     - .:/home/node/app
    #   depends_on:
    #     - db
    # db:
    #   image: postgres:alpine
    #   container_name: postgresql
    #   restart: always
    #   ports:
    #     - 5432:5432
    #   volumes:
    #     - dbdata:/var/lib/postgresql/data
    #   environment:
    #     - POSTGRES_PASSWORD=docker
    #     - POSTGRES_DB=postgres
